services:
  server:
    build:
      context: .
      target: develop
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - database
    volumes:
      - .:/app
  database:
    image: postgres:17.0
    container_name: map-of-treasures-backend-database-1
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - '8000:8080'
volumes:
  pgdata:
    driver: local